### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:2)

### ISSUE THREAD

**Issue by RealmX1** [kihlh/hmc-win32#78]
⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET / 500 in 10ms
 ⨯ ./node_modules/hmc-win32/bin/HMC@Beta_x64.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Reproducing: create new node.js project, install with `npm i hmc-win32` and `npm i react`
`/app/page.tsx`:
```tsx
import {WindowTracker} from '@/components/test'

export default function Home() {
  return <div>
    asdf
    <WindowTracker />
  </div>
}
```

`/components/test.tsx/`:
```tsx
'use client'

import React, { useState, useEffect } from 'react';
import HMC from 'hmc-win32';

interface WindowInfo {
  hWnd: number;
  title: string;
  isVisible: boolean;
  processId: number;
  processName: string;
}

export function WindowTracker() {
    const value = HMC.isAdmin()
    return <div>{value}</div>
}
```

Chrome developer console shows the following:
![image](https://github.com/user-attachments/assets/0a190640-7926-4454-a14a-3181c73f60be)
```console
GET http://localhost:3000/ 500 (Internal Server Error)Understand this error
index.js:625 Uncaught ModuleParseError: Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\webpack\bundle5.js:28:403799)
    at <unknown> (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\webpack\bundle5.js:28:405546)
    at processResult (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\webpack\bundle5.js:28:401241)
    at <unknown> (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\webpack\bundle5.js:28:402302)
    at <unknown> (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8727)
    at iterateNormalLoaders (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5565)
    at <unknown> (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5426)
    at <unknown> (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\webpack\bundle5.js:28:401777)
    at eval (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\compiled\webpack\bundle5.js:13:28858)
    at <unknown> (file://C:\Users\zhang\Desktop\github\Trace-of-Thought\app-js\window-tracker\node_modules\next\dist\build\webpack\plugins\profiling-plugin.js:179:29)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
getServerError @ nodeStackFrames.js:38
eval @ index.js:625
setTimeout
hydrate @ index.js:613
await in hydrate
pageBootrap @ page-bootstrap.js:27
eval @ next-dev.js:25
Promise.then
eval @ next-dev.js:23
./node_modules/next/dist/client/next-dev.js @ main.js:820
options.factory @ webpack.js:647
__webpack_require__ @ webpack.js:37
__webpack_exec__ @ main.js:1964
(anonymous) @ main.js:1965
webpackJsonpCallback @ webpack.js:1195
(anonymous) @ main.js:9
Show 6 more frames
Show lessUnderstand this error
websocket.js:39 [HMR] connected
hydration-error-info.js:63 ./node_modules/hmc-win32/bin/HMC@Beta_x64.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
console.error @ hydration-error-info.js:63
window.console.error @ setup-hydration-warning.js:18
handleErrors @ hot-reloader-client.js:162
processMessage @ hot-reloader-client.js:239
eval @ hot-reloader-client.js:67
handleMessage @ websocket.js:45
Show 6 more frames
Show lessUnderstand this error
hydration-error-info.js:63 ./node_modules/hmc-win32/bin/HMC@Beta_x86.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
console.error @ hydration-error-info.js:63
window.console.error @ setup-hydration-warning.js:18
handleErrors @ hot-reloader-client.js:162
processMessage @ hot-reloader-client.js:239
eval @ hot-reloader-client.js:67
handleMessage @ websocket.js:45
Show 6 more frames
Show lessUnderstand this error
hydration-error-info.js:63 ./node_modules/hmc-win32/bin/HMC_x64.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
console.error @ hydration-error-info.js:63
window.console.error @ setup-hydration-warning.js:18
handleErrors @ hot-reloader-client.js:162
processMessage @ hot-reloader-client.js:239
eval @ hot-reloader-client.js:67
handleMessage @ websocket.js:45
Show 6 more frames
Show lessUnderstand this error
hydration-error-info.js:63 ./node_modules/hmc-win32/bin/HMC_x86.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
console.error @ hydration-error-info.js:63
window.console.error @ setup-hydration-warning.js:18
handleErrors @ hot-reloader-client.js:162
processMessage @ hot-reloader-client.js:239
eval @ hot-reloader-client.js:67
handleMessage @ websocket.js:45
Show 6 more frames
Show lessUnderstand this error
```

**Comment by kihlh** [comment]
This issue may arise because Webpack is attempting to parse a .node binary file (which is native code) as a JavaScript file. Since this file is binary rather than JS, it leads to the "invalid character" error. By default, Webpack is not equipped to handle .node files. The hmc-win32 module is a standard Node.js module implemented in C++ (using the N-API in C language), and it is specifically designed to run in a Node.js environment. It is not suitable for use in a browser environment, but it can be invoked within the Electron framework.

**Comment by kihlh** [comment]
If you are indeed using a Node.js or Electron environment with a Node.js version higher than 6, you need to address another issue: by default, Webpack cannot handle .node files. You need to configure externals to instruct Webpack not to bundle certain modules (such as native modules), and instead allow Node.js to dynamically load them at runtime.

Ensure server-side usage: Native Node.js modules like hmc-win32 are designed to run in a Node.js environment, not in a browser environment. Since you are using this module inside a React component (WindowTracker), this could be problematic. Native Node modules cannot run in the browser because they rely on underlying operating system dependencies.

You should ensure that the parts of your code interacting with the hmc-win32 module only run on the server-side (Node.js environment) and not on the client-side (browser).


   
   ```js
   // webpack.config.js
   module.exports = {
     // 其他配置选项...
     externals: {
       'hmc-win32': 'commonjs hmc-win32',
     },
   };
   ```
